replicaCount: 2

service:
  type: NodePort
  containerPort: 8080
  externalPort: 80
  host: dev.k8s-sample.yourdomain.com

healthCheckPath: /health
requestedMemory: "100Mi"
requestedCpu: "250m"
# memoryLimit: "200Mi"
# cpuLimit: "500m"

# autoscaling section
hpa:
  cpu: 30
  maxReplicas: 10
  enabled: true
